In [5]:
# Transaction Analysis

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## 1. Load Data
# Define file ranges
start, end = 50, 61  # Adjust these variables to load specific files

# Load the PositionsMerge and PositionsSplit data
positions_merge = pd.read_csv(f'positionsmerge_events/positionsmerge_{start}-{end}.csv')
positions_split = pd.read_csv(f'positionsplit_events/positionsplit_{start}-{end}.csv')

# Display the loaded data
print("PositionsMerge Data:")
display(positions_merge.head())

print("\nPositionsSplit Data:")
display(positions_split.head())

## 2. Data Preprocessing
# Ensure that the `amount` column is numeric and handle any missing values if necessary.
positions_merge['amount'] = pd.to_numeric(positions_merge['amount'], errors='coerce')
positions_split['amount'] = pd.to_numeric(positions_split['amount'], errors='coerce')

positions_merge = positions_merge.dropna(subset=['amount'])
positions_split = positions_split.dropna(subset=['amount'])

positions_merge['conditionId'] = positions_merge['conditionId'].astype(str)
positions_split['conditionId'] = positions_split['conditionId'].astype(str)

## 3. Summarize Total PositionsMerged and PositionsSplit
total_merged = positions_merge['amount'].sum()
total_split = positions_split['amount'].sum()

print(f"Total PositionsMerged Amount: {total_merged}")
print(f"Total PositionsSplit Amount: {total_split}")

## 4. Group by `conditionId`
merge_by_condition = positions_merge.groupby('conditionId')['amount'].sum().reset_index().rename(columns={'amount': 'total_merged'})
split_by_condition = positions_split.groupby('conditionId')['amount'].sum().reset_index().rename(columns={'amount': 'total_split'})

print("PositionsMerged by conditionId:")
display(merge_by_condition)

print("\nPositionsSplit by conditionId:")
display(split_by_condition)

## 5. Merge the Grouped DataFrames and Calculate Difference
merged_data = pd.merge(split_by_condition, merge_by_condition, on='conditionId', how='outer')
merged_data['total_split'] = merged_data['total_split'].fillna(0)
merged_data['total_merged'] = merged_data['total_merged'].fillna(0)
merged_data['split_minus_merge'] = merged_data['total_split'] - merged_data['total_merged']

print("Merged Data with Differences:")
display(merged_data)

## 6. Top 5 `conditionId`s Based on Difference
top_5 = merged_data.sort_values(by='split_minus_merge', ascending=False).head(5)
print("Top 5 conditionIds by (PositionsSplit - PositionsMerge):")
display(top_5)

## 7. Calculate Total Liquidity
total_liquidity = total_split + total_merged
print(f"Total Liquidity: {total_liquidity}")

## 8. Summary
print(f"Total PositionsMerged Amount: {total_merged}")
print(f"Total PositionsSplit Amount: {total_split}")
print(f"Total Liquidity: {total_liquidity}")

print("\nTop 5 conditionIds by (PositionsSplit - PositionsMerge):")
display(top_5)

PositionsMerge Data:

,event,blockNumber,txIndex,stakeholder,collateralToken,parentCollectionId,conditionId,amount
0,PositionsMerge,51670712,53,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,3a3bd7bb9528e159577f7c2e685cc81a765002e2,0x00000000000000000000000000000000000000000000...,0xbdc8ad55cb8fa7b3c84a971d6056f6a0f354f0f882c3...,10.000
1,PositionsMerge,51693528,32,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,3a3bd7bb9528e159577f7c2e685cc81a765002e2,0x00000000000000000000000000000000000000000000...,0xbdc8ad55cb8fa7b3c84a971d6056f6a0f354f0f882c3...,2.142
2,PositionsMerge,51953990,73,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,3a3bd7bb9528e159577f7c2e685cc81a765002e2,0x00000000000000000000000000000000000000000000...,0x696baf880832d000a37ea87cc94235b1ac58e7e9fe7a...,10.000
3,PositionsMerge,51954000,134,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,3a3bd7bb9528e159577f7c2e685cc81a765002e2,0x00000000000000000000000000000000000000000000...,0x696baf880832d000a37ea87cc94235b1ac58e7e9fe7a...,3.500
4,PositionsMerge,51954006,89,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,3a3bd7bb9528e159577f7c2e685cc81a765002e2,0x00000000000000000000000000000000000000000000...,0x696baf880832d000a37ea87cc94235b1ac58e7e9fe7a...,10.000

PositionsSplit Data:

,event,blockNumber,txIndex,stakeholder,parentCollectionId,conditionId,collateralToken,amount,partition
0,PositionSplit,51408357,79,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,0x00000000000000000000000000000000000000000000...,0xbdc8ad55cb8fa7b3c84a971d6056f6a0f354f0f882c3...,0x3a3bd7bb9528e159577f7c2e685cc81a765002e2,0.537634,"(1, 2)"
1,PositionSplit,51430964,51,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,0x00000000000000000000000000000000000000000000...,0x3dde8cb914fde7cf905a07b701892ea2ead3e3276c77...,0x3a3bd7bb9528e159577f7c2e685cc81a765002e2,20.500000,"(1, 2)"
2,PositionSplit,51430980,57,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,0x00000000000000000000000000000000000000000000...,0x66ef06c609eeecec69bca1057f4b2eda2e1fc8e9ded8...,0x3a3bd7bb9528e159577f7c2e685cc81a765002e2,20.500000,"(1, 2)"
3,PositionSplit,51444790,62,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,0x00000000000000000000000000000000000000000000...,0x3dde8cb914fde7cf905a07b701892ea2ead3e3276c77...,0x3a3bd7bb9528e159577f7c2e685cc81a765002e2,0.114942,"(1, 2)"
4,PositionSplit,51444821,43,0xd91e80cf2e7be2e162c6513ced06f1dd0da35296,0x00000000000000000000000000000000000000000000...,0x66ef06c609eeecec69bca1057f4b2eda2e1fc8e9ded8...,0x3a3bd7bb9528e159577f7c2e685cc81a765002e2,0.555555,"(1, 2)"

Total PositionsMerged Amount: 9988630.878035203
Total PositionsSplit Amount: 34791623.5176416
PositionsMerged by conditionId:

                                            conditionId  total_merged
0     0x00170a925d97ede2ef8ac1c2dc4bc176ee011482b356...    721.894000
1     0x0043a0a5f85400263a0cd045332ae8b0ae5433cef663...     45.500000
2     0x004e19d419d05dd366793689ce2af457d51bc921d9da...     78.637000
3     0x0051ea6db91583770e996964a086c1817c4527d9307c...     30.514000
4     0x0059f5405d768fb411aa56a59867a540d552d03407bb...     56.930000
...                                                 ...           ...
2400  0xff4b4953a9726c957d25aaf2993e9492b4c7e8d9098f...    544.400000
2401  0xff5c1e73e31ad495136fcafce90710a3a1771a96f071...  13856.115000
2402  0xff5c9bdba314a13244c33e3cfb98cd66951d602af96e...   1030.356000
2403  0xff7cd573927f01a491608361461bed7cfe60b86278ba...    327.381000
2404  0xfff55467fd4684d17e8fa7f85e4afbab169a95ffbc7e...    271.524654

[2405 rows x 2 columns]

PositionsSplit by conditionId:

                                            conditionId   total_split
0     0x00170a925d97ede2ef8ac1c2dc4bc176ee011482b356...  12705.741882
1     0x00289840c4263f68f5aadacb76922fce1665a2cce50d...    637.688156
2     0x002d5b0a5eeb0a72c09549f1101b2ce530ccbd8a3aa4...     77.656006
3     0x0043a0a5f85400263a0cd045332ae8b0ae5433cef663...    339.332314
4     0x004e19d419d05dd366793689ce2af457d51bc921d9da...   1109.967020
...                                                 ...           ...
3840  0xff5c1e73e31ad495136fcafce90710a3a1771a96f071...  39365.235716
3841  0xff5c9bdba314a13244c33e3cfb98cd66951d602af96e...   1093.628150
3842  0xff7cd573927f01a491608361461bed7cfe60b86278ba...   1994.108920
3843  0xffdac560d86877634249a40744ed53a0758712439fe2...      9.000000
3844  0xfff55467fd4684d17e8fa7f85e4afbab169a95ffbc7e...   2354.981533

[3845 rows x 2 columns]

Merged Data with Differences:

,conditionId,total_split,total_merged,split_minus_merge
0,0x00170a925d97ede2ef8ac1c2dc4bc176ee011482b356...,12705.741882,721.894000,11983.847882
1,0x00289840c4263f68f5aadacb76922fce1665a2cce50d...,637.688156,0.000000,637.688156
2,0x002d5b0a5eeb0a72c09549f1101b2ce530ccbd8a3aa4...,77.656006,0.000000,77.656006
3,0x0043a0a5f85400263a0cd045332ae8b0ae5433cef663...,339.332314,45.500000,293.832314
4,0x004e19d419d05dd366793689ce2af457d51bc921d9da...,1109.967020,78.637000,1031.330020
...,...,...,...,...
3840,0xff5c1e73e31ad495136fcafce90710a3a1771a96f071...,39365.235716,13856.115000,25509.120716
3841,0xff5c9bdba314a13244c33e3cfb98cd66951d602af96e...,1093.628150,1030.356000,63.272150
3842,0xff7cd573927f01a491608361461bed7cfe60b86278ba...,1994.108920,327.381000,1666.727920
3843,0xffdac560d86877634249a40744ed53a0758712439fe2...,9.000000,0.000000,9.000000
3844,0xfff55467fd4684d17e8fa7f85e4afbab169a95ffbc7e...,2354.981533,271.524654,2083.456879

Top 5 conditionIds by (PositionsSplit - PositionsMerge):

,conditionId,total_split,total_merged,split_minus_merge
3316,0xdd22472e552920b8438158ea7238bfadfa4f736aa4ce...,3.013053e+06,978545.335323,2.034508e+06
2339,0x9e9071636d176562592a98dfede865385ba0cff7864c...,1.680207e+06,392529.013000,1.287678e+06
2960,0xc6485bb7ea46d7bb89beb9c91e7572ecfc72a6273789...,1.418430e+06,239857.328000,1.178572e+06
679,0x2d606a51f902a4d934a4b810dd77cb28bb8e40268f42...,1.491183e+06,375359.925011,1.115823e+06
1487,0x653483009043f1663360bc35ed8fb542d3f945391608...,1.692718e+06,917828.473383,7.748898e+05

Total Liquidity: 44780254.3956768
Total PositionsMerged Amount: 9988630.878035203
Total PositionsSplit Amount: 34791623.5176416
Total Liquidity: 44780254.3956768

Top 5 conditionIds by (PositionsSplit - PositionsMerge):

,conditionId,total_split,total_merged,split_minus_merge
3316,0xdd22472e552920b8438158ea7238bfadfa4f736aa4ce...,3.013053e+06,978545.335323,2.034508e+06
2339,0x9e9071636d176562592a98dfede865385ba0cff7864c...,1.680207e+06,392529.013000,1.287678e+06
2960,0xc6485bb7ea46d7bb89beb9c91e7572ecfc72a6273789...,1.418430e+06,239857.328000,1.178572e+06
679,0x2d606a51f902a4d934a4b810dd77cb28bb8e40268f42...,1.491183e+06,375359.925011,1.115823e+06
1487,0x653483009043f1663360bc35ed8fb542d3f945391608...,1.692718e+06,917828.473383,7.748898e+05

In [10]:
## 9. Load Market Data and Merge
# Load the all_market_data.json file
import json

# Assuming 'all_market_data.json' is in the same directory
with open('gamma-market/all_market_data.json', 'r') as f:
    market_data_json = json.load(f)

# Convert the JSON data into a DataFrame
market_data = pd.DataFrame(market_data_json)

# Extract relevant columns
market_info = market_data[['conditionId', 'question', 'volume', 'outcomes']]

# Ensure conditionId is of type string
market_info['conditionId'] = market_info['conditionId'].astype(str)

# Merge the market information with your merged_data DataFrame
merged_with_market = pd.merge(merged_data, market_info, on='conditionId', how='left')

# Display the merged DataFrame
print("Merged Data with Market Information:")
display(merged_with_market)

Merged Data with Market Information:

/var/folders/5g/44lbr4md28sc24qvvyvgppqr0000gn/T/ipykernel_83255/688305043.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  market_info['conditionId'] = market_info['conditionId'].astype(str)

,conditionId,total_split,total_merged,split_minus_merge,question,volume,outcomes
0,0x00170a925d97ede2ef8ac1c2dc4bc176ee011482b356...,12705.741882,721.894000,11983.847882,NaN,NaN,NaN
1,0x00289840c4263f68f5aadacb76922fce1665a2cce50d...,637.688156,0.000000,637.688156,NaN,NaN,NaN
2,0x002d5b0a5eeb0a72c09549f1101b2ce530ccbd8a3aa4...,77.656006,0.000000,77.656006,Will Wolverhampton beat Arsenal?,930.130058,"[""Yes"", ""No""]"
3,0x0043a0a5f85400263a0cd045332ae8b0ae5433cef663...,339.332314,45.500000,293.832314,NaN,NaN,NaN
4,0x004e19d419d05dd366793689ce2af457d51bc921d9da...,1109.967020,78.637000,1031.330020,NaN,NaN,NaN
...,...,...,...,...,...,...,...
3840,0xff5c1e73e31ad495136fcafce90710a3a1771a96f071...,39365.235716,13856.115000,25509.120716,NaN,NaN,NaN
3841,0xff5c9bdba314a13244c33e3cfb98cd66951d602af96e...,1093.628150,1030.356000,63.272150,NaN,NaN,NaN
3842,0xff7cd573927f01a491608361461bed7cfe60b86278ba...,1994.108920,327.381000,1666.727920,NaN,NaN,NaN
3843,0xffdac560d86877634249a40744ed53a0758712439fe2...,9.000000,0.000000,9.000000,Will Notre Dame win the 2025 College Football ...,139160.616077,"[""Yes"", ""No""]"
3844,0xfff55467fd4684d17e8fa7f85e4afbab169a95ffbc7e...,2354.981533,271.524654,2083.456879,NaN,NaN,NaN

In [11]:
## 10. Compare Liquidity
# Convert 'volume' from string to numeric, handling any errors
merged_with_market['volume'] = pd.to_numeric(merged_with_market['volume'], errors='coerce').fillna(0)

# Calculate the total liquidity from your calculations
merged_with_market['calculated_liquidity'] = merged_with_market['total_split'] + merged_with_market['total_merged']

# Compare the liquidity from JSON vs. calculated
merged_with_market['liquidity_difference'] = merged_with_market['volume'] - merged_with_market['calculated_liquidity']

# Display the DataFrame with the liquidity comparison
print("Liquidity Comparison:")
display(merged_with_market[['conditionId', 'question', 'volume', 'calculated_liquidity', 'liquidity_difference']])

Liquidity Comparison:

,conditionId,question,volume,calculated_liquidity,liquidity_difference
0,0x00170a925d97ede2ef8ac1c2dc4bc176ee011482b356...,NaN,0.000000,13427.635882,-13427.635882
1,0x00289840c4263f68f5aadacb76922fce1665a2cce50d...,NaN,0.000000,637.688156,-637.688156
2,0x002d5b0a5eeb0a72c09549f1101b2ce530ccbd8a3aa4...,Will Wolverhampton beat Arsenal?,930.130058,77.656006,852.474052
3,0x0043a0a5f85400263a0cd045332ae8b0ae5433cef663...,NaN,0.000000,384.832314,-384.832314
4,0x004e19d419d05dd366793689ce2af457d51bc921d9da...,NaN,0.000000,1188.604020,-1188.604020
...,...,...,...,...,...
3840,0xff5c1e73e31ad495136fcafce90710a3a1771a96f071...,NaN,0.000000,53221.350716,-53221.350716
3841,0xff5c9bdba314a13244c33e3cfb98cd66951d602af96e...,NaN,0.000000,2123.984150,-2123.984150
3842,0xff7cd573927f01a491608361461bed7cfe60b86278ba...,NaN,0.000000,2321.489920,-2321.489920
3843,0xffdac560d86877634249a40744ed53a0758712439fe2...,Will Notre Dame win the 2025 College Football ...,139160.616077,9.000000,139151.616077
3844,0xfff55467fd4684d17e8fa7f85e4afbab169a95ffbc7e...,NaN,0.000000,2626.506187,-2626.506187

In [12]:
## 11. Top 5 ConditionIds with Market Info
# Get the top 5 based on 'split_minus_merge'
top_5_with_market = merged_with_market.sort_values(by='split_minus_merge', ascending=False).head(5)

print("Top 5 conditionIds with Market Information:")
display(top_5_with_market[['conditionId', 'question', 'total_split', 'total_merged', 'split_minus_merge', 'volume', 'calculated_liquidity', 'liquidity_difference']])

Top 5 conditionIds with Market Information:

,conditionId,question,total_split,total_merged,split_minus_merge,volume,calculated_liquidity,liquidity_difference
3316,0xdd22472e552920b8438158ea7238bfadfa4f736aa4ce...,NaN,3.013053e+06,978545.335323,2.034508e+06,0.0,3.991598e+06,-3.991598e+06
2339,0x9e9071636d176562592a98dfede865385ba0cff7864c...,NaN,1.680207e+06,392529.013000,1.287678e+06,0.0,2.072736e+06,-2.072736e+06
2960,0xc6485bb7ea46d7bb89beb9c91e7572ecfc72a6273789...,NaN,1.418430e+06,239857.328000,1.178572e+06,0.0,1.658287e+06,-1.658287e+06
679,0x2d606a51f902a4d934a4b810dd77cb28bb8e40268f42...,NaN,1.491183e+06,375359.925011,1.115823e+06,0.0,1.866542e+06,-1.866542e+06
1487,0x653483009043f1663360bc35ed8fb542d3f945391608...,NaN,1.692718e+06,917828.473383,7.748898e+05,0.0,2.610547e+06,-2.610547e+06